### PR TITLE
Ported to Python3

### PR DESCRIPTION
**Pull request by DavidMoraisFerreira**
Ported the py script to Python3. (Tested with Python 3.4.6)

### CODE REVIEW

**Review by capiscuas — APPROVED** [review]
Great thanks!!

**Comment by capiscuas** [comment]
Did you actually tried for some real data migration?

**Comment by DavidMoraisFerreira** [comment]
The fiji_level8 dataset you provided seemed to be correct in JOSM. I am working on importing admin_level=10 boundaries for Portugal (into existing admin_level=8 / admin_level=9 boundaries) and your python script is really helpful to figure out how to work with OSM/SHP with Python.

Would it be possible for you to add a LICENSE to your project?

**Comment by capiscuas** [comment]
Done, thanks for remind me. I added AGPLv3 (in case somebody tries to make an online tool too to be forced to opensource the code too)

Let me know if you need help figuring out how to merge those different layers.
I wanted to make the script more generic if possible.

**Comment by DavidMoraisFerreira** [comment]
Will do, thanks!

**Pull request merged**
